name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      env:
        connectionstring: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Set UserSecret
      run: dotnet user-secrets set "AZURE_SQL_CONNECTIONSTRING" "$connectionstring"
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal