name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.401

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)

          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os win -c Release -o "App-$tag-windows"
          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os linux -c Release -o "App-$tag-linux"
          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os osx -c Release -o "App-$tag-macos"

          # Pack files
         
          # Pack to zip for Windows
          7z a -tzip "App-$tag-windows.zip" ./"App-$tag-windows/*"
          7z a -tzip "App-$tag-linux.zip" "./App-$tag-linux/*"
          7z a -tzip "App-$tag-macos.zip" "./App-$tag-macos/*"


          # Delete output directory
          rm -r "App-$tag-windows"
          rm -r "App-$tag-linux"
          rm -r "App-$tag-macos"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          