name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.401

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)

          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os win -c Release -p:PublishSingleFile=true -o "Chirp-$tag-windows" --self-contained false
          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os linux -c Release -p:PublishSingleFile=true -o "Chirp-$tag-linux" --self-contained false
          # Build everything
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj --framework net7.0 --os osx -c Release -p:PublishSingleFile=true -o "Chirp-$tag-macos" --self-contained false


          # Pack to zip for Windows
          7z a -tzip "Chirp-$tag-windows.zip" "./Chirp-$tag-windows/*"
          7z a -tzip "Chirp-$tag-linux.zip" "./Chirp-$tag-linux/*"
          7z a -tzip "Chirp-$tag-macos.zip" "./Chirp-$tag-macos/*"


          # Delete output directory
          rm -r "Chirp-$tag-windows"
          rm -r "Chirp-$tag-linux"
          rm -r "Chirp-$tag-macos"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "App*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
